apiVersion: v1
kind: Secret
metadata:
  name: wikijs-runtime-config
  namespace: wikijs
type: Opaque
stringData:
  DB_TYPE: "postgres"
  DB_HOST: "__WIKIJS_POSTGRES_HOST__"
  DB_PORT: "__WIKIJS_POSTGRES_PORT__"
  DB_NAME: "__WIKIJS_POSTGRES_DATABASE__"
  DB_USER: "__WIKIJS_POSTGRES_USER__"
  DB_PASS: "__WIKIJS_POSTGRES_PASSWORD__"
  MINIO_ENDPOINT: "__WIKIJS_MINIO_ENDPOINT__"
  MINIO_PORT: "__WIKIJS_MINIO_PORT__"
  MINIO_BUCKET: "__WIKIJS_MINIO_BUCKET__"
  MINIO_ACCESS_KEY: "__WIKIJS_MINIO_ACCESS_KEY__"
  MINIO_SECRET_KEY: "__WIKIJS_MINIO_SECRET_KEY__"
