apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spark

resources:
  - servicemonitor.yaml

helmCharts:
  - name: spark-kubernetes-operator
    releaseName: spark-operator
    repo: https://apache.github.io/spark-kubernetes-operator
    version: 1.6.0
    namespace: spark
    valuesFile: values.yaml
