apiVersion: v1
kind: Secret
metadata:
  name: mongo-auth
  namespace: mongo
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: "__MONGO_ROOT_USERNAME__"
  MONGO_INITDB_ROOT_PASSWORD: "__MONGO_ROOT_PASSWORD__"
