apiVersion: v1
kind: Secret
metadata:
  name: minio-s3-credentials
  namespace: spark
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "__MINIO_ACCESS_KEY__"
  AWS_SECRET_ACCESS_KEY: "__MINIO_SECRET_KEY__"
