service:
  type: ClusterIP

config:
  inCluster: true
  oidc:
    secret:
      create: false

serviceAccount:
  create: true
  name: headlamp-admin

clusterRoleBinding:
  create: true
  clusterRoleName: cluster-admin
