apiVersion: v1
kind: ResourceQuota
metadata:
  name: spark-quota
  namespace: spark
spec:
  hard:
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "15"
    limits.memory: 30Gi
    persistentvolumeclaims: "10"
    pods: "50"
