apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubelet-metrics-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubelet-metrics-proxy
subjects:
  - kind: ServiceAccount
    name: kubelet-metrics-proxy
    namespace: observability
