prometheusScrape: true

service:
  type: NodePort
  port: 8080
  nodePort: 30080

prometheus:
  monitor:
    enabled: false

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi

podLabels:
  app.kubernetes.io/part-of: observability
