apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-state-metrics
  namespace: observability
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  rules:
    - host: kube-state-metrics.<homelab-domain>
      http:
        paths:
          - path: /metrics
            pathType: Prefix
            backend:
              service:
                name: kube-state-metrics
                port:
                  number: 8080
  tls:
    - hosts:
        - kube-state-metrics.<homelab-domain>
      secretName: <private-ingress-tls-secret>
