apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-state-metrics
  namespace: observability
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  rules:
    - host: __KUBE_STATE_METRICS_HOST__
      http:
        paths:
          - path: /metrics
            pathType: Prefix
            backend:
              service:
                name: kube-state-metrics
                port:
                  number: 8080
  tls:
    - hosts:
        - __KUBE_STATE_METRICS_HOST__
      secretName: __INGRESS_TLS_SECRET_NAME__
